### PR TITLE
Enable logging by default and 5 second execution for automated testing

### PR DESCRIPTION
**Pull request by berndmweber**
This doesn't change the original way this application executed but adds the ability to start it with --test and thereby running it for a predefined amount of time to collect the execution output. This allows for automated testing.

### CODE REVIEW

**Comment by goeblr** [comment]
Thanks for the work towards testing!

Depending on which aspect we want to test, I fear this way might lead to inconsistencies in the results, mostly because there are no guarantuees on how many messages are processed overall. For that there are two mechanisms already in place:
 * The parameters "streamSequenceOnce" of "UltrasoundInterfaceBeamformedMock" and "UltrasoundInterfaceRawDataMock" which allow the SupraExecutor to exit after all messages were sent from the inputs and processed.
 * The "AutoQuitNode" that stops the pipeline after a certain number of received messages.

Additionally, SupraManager creates the nodes configured to not drop any frames (as opposed to the usually preferred frame drop for live use).

Does that help with the testing you have in mind?

Regarding logging: This might also be better located in the SupraExecutor, I don't see the need to have that in the commandline interface. Is there a reason to prefer the standard output over the log-file for that?

**Comment by berndmweber** [comment]
Hey Ruediger,
Thanks for the input.

- Is there an example of this configuration with these parameters to look at somewhere?
- Same question for the file logging. It's not obvious to me how that can be activated. I have no specific need for std:out, in fact I was piping the output into a log file to further analyze.

The point I was trying to get to with the testing is that I can build then run a demo or test pipeline (currently just using the configDemo.xml configuration in the data directory) to verify that the executable can run and is exercising the CUDA libraries on Tegra. So no issue with using SupraExecutor instead.

Based on above questions I guess I'm missing some minimal instruction set/documentation that explains how this is hooked together. I may just not be seeing it though.

Thanks!

**Comment by goeblr** [comment]
I agree, documentation is still incomplete.

- The first option (having the input only send the input images once) can be acheived by adding `<param name="streamSequenceOnce" type="bool">1</param>` to the node "US-Mock" in configDemo.xml (see the full file below)
- The log is always written to the working directory, as "supra.log". No need to activate anything for that.


[test.xml](https://github.com/IFL-CAMP/supra/files/3347250/test.txt)

**Comment by goeblr** [comment]
Does the described method work for you?
If yes, I would close this.

**Pull request closed without merging**
